#!/bin/bash
exec 2>&1
# http://www.hnwatcher.com/r/1539872/Using-Runit-in-a-Docker-Container
source /etc/envvars
exec mono $APP_ROOT/$APP_NAME /applications=/:$APP_ROOT /socket=tcp:127.0.0.1:$FASTCGI_PORT /printlog=True
